services:
  mongodb:
    image: mongo:latest
    container_name: displaymongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  springboot-app:
    image: spring-app
    container_name: springboot-app
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/displayDB
    depends_on:
      - mongodb

volumes:
  mongo-data:
